# CHANGE: replace /home/magnus with your home directory
preload = /home/magnus/.config/wallpapers/Tank-Girl-Wallpaper-Black.png
wallpaper = DP-3,/home/magnus/.config/wallpapers/Tank-Girl-Wallpaper-Black.png
splash = false
