source = ~/.local/state/dotfiles-theme/hyprlock.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    color = $theme_background
    blur_passes = 1
    blur_size = 3
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 300, 50
    rounding = 0
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 1
    outer_color = $theme_border
    inner_color = $theme_surface
    font_color = $theme_foreground
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = true
    placeholder_text = <i>Passwort...</i>
    placeholder_color = $theme_muted
    check_color = $theme_accent
    fail_color = $theme_danger
    fail_text = <i>Falsch</i>
    capslock_color = $theme_warning
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $theme_accent
    font_size = 64
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}
